version: "3.7"
services:
  backend:
    build: .
    ports:
      - "8080:8080"
  postgres:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
    volumes:
    - /tmp/postgresql/data:/var/lib/postgresql/data
